services:
  # Service pour l'API NestJS.
  app:
    # On utilise l'image du Dockerfile.
    build: .
    container_name: castled-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # On expose le port de l'application.
    # Généralement, le port 3000 est utilisé.
    # On utilise la variable d'environnement définie dans le fichier .env.
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
    networks:
      - castled_api

  # Service pour la base de données PostgreSQL.
  postgres:
    image: postgres:latest
    container_name: castled-postgres
    # On expose le port de la base de données.
    # Généralement, le port 5432 est utilisé.
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    # On définit les variables d'environnement.
    # Elles sont présentes dans le fichier .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - castled_api

volumes:
  postgres_data:

networks:
  castled_api:
