services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443' # Ajoutez le port 443 pour HTTPS
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/ssl/server.crt:/etc/nginx/server.crt' # Ajoutez le certificat SSL
      - './nginx/ssl/server.key:/etc/nginx/server.key' # Ajoutez la clé SSL
    networks:
      - castled_api_network
    depends_on:
      - app

  #
  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - castled_api_network

  # Service pour la base de données PostgreSQL
  db:
    image: postgres:latest
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    networks:
      - castled_api_network

volumes:
  db_data:

networks:
  castled_api_network:
